

// We don't use an Enum, because:
// 1. The enum elements must be uppercase, which is annoying;
// 2. Integers are good for doing ad-hoc hacks (because of larger ranges).
pub let zero = 0;
pub let ra = 1;
pub let sp = 2;
pub let gp = 3;
pub let tp = 4;
pub let t0 = 5;
pub let t1 = 6;
pub let t2 = 7;
pub let s0 = 8;
pub let s1 = 9;
pub let a0 = 10;
pub let a1 = 11;
pub let a2 = 12;
pub let a3 = 13;
pub let a4 = 14;
pub let a5 = 15;
pub let a6 = 16;
pub let a7 = 17;
pub let s2 = 18;
pub let s3 = 19;
pub let s4 = 20;
pub let s5 = 21;
pub let s6 = 22;
pub let s7 = 23;
pub let s8 = 24;
pub let s9 = 25;
pub let s10 = 26;
pub let s11 = 27;
pub let t3 = 28;
pub let t4 = 29;
pub let t5 = 30;
pub let t6 = 31;
